version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: EcomMMS.API/Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - postgres
      - redis
      - seq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=ecommms;Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - Redis__ConnectionString=redis:6379
      - Seq__ServerUrl=http://seq:5341
    networks:
      - ecommms-network

  seq:
    image: datalust/seq:latest
    ports:
      - "5341:80"
      - "5342:5341"
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_NOAUTHENTICATION=true
    volumes:
      - seq_data:/data
    networks:
      - ecommms-network

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ecommms
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ecommms-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ecommms-network

volumes:
  postgres_data:
  redis_data:
  seq_data:

networks:
  ecommms-network:
    driver: bridge 