version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: EcomMMS.API/Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - postgres
      - redis
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=ecommms;Username=postgres;Password=postgres
      - Redis__ConnectionString=redis:6379
    networks:
      - ecommms-network

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ecommms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ecommms-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ecommms-network

volumes:
  postgres_data:
  redis_data:

networks:
  ecommms-network:
    driver: bridge 